import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Imprima } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });
const impr = Imprima({
  weight: "400",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={impr.className + ' antialiased'} >
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
